<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fs</string>
	</array>
	<key>name</key>
	<string>MagicFS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\A[\s]*;.*</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.double.slash</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`[^']*'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@?IF(?:\{)</string>
			<key>name</key>
			<string>keyword.control.if</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@?DO(?:\{)</string>
			<key>name</key>
			<string>keyword.control.do</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\A:.*</string>
			<key>name</key>
			<string>entity.name.section.member.title</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[A-Z][A-z]</string>
			<key>name</key>
			<string>support.function.intrinsic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[a-z][A-z]</string>
			<key>name</key>
			<string>support.class.extrinsic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[A-z][0-9]+</string>
			<key>name</key>
			<string>support.function.list.manipulation</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[0-9]+</string>
			<key>name</key>
			<string>support.type.code.member</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[A-Z]</string>
			<key>name</key>
			<string>variable.other.local</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-z]</string>
			<key>name</key>
			<string>variable.parameter.global</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\d]\.*</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@?(\{|\}|\[|\]|\(|\))</string>
			<key>name</key>
			<string>keyword.control.brackets</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@?(\^|\_|\&amp;|\!|\=|\+|\-|\/|\\|\*|\%|\$|\#|\'|\&lt;|\&gt;|\|[0-9]*|\~)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fs</string>
	<key>uuid</key>
	<string>9ac84646-8faf-4939-bd4e-4297c01e210a</string>
</dict>
</plist>
